// Fase 2/Evidencias Proyecto/Evidencias de sistema Aplicación/Plataforma de Gestión Escolar/src/components/StudentView.tsx
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Progress } from './ui/progress';
import { Tabs, TabsContent, TabsList, TabsTrigger } from './ui/tabs';
import { 
  User, 
  Calendar, 
  BookOpen, 
  TrendingUp, 
  Clock,
  CheckCircle,
  XCircle,
  AlertTriangle
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { 
  mockStudents, 
  mockGrades, 
  mockAttendance, 
  mockAnnotations 
} from '../data/mockData';

export const StudentView: React.FC = () => {
  const { user } = useAuth();

  if (!user || user.role !== 'apoderado') return null;

  const myStudents = mockStudents.filter(s => s.guardianId === user.id);

  const getStudentData = (studentId: string) => {
    const grades = mockGrades.filter(g => g.studentId === studentId);
    const attendance = mockAttendance.filter(a => a.studentId === studentId);
    const annotations = mockAnnotations.filter(a => a.studentId === studentId);

    const attendanceRate = attendance.length > 0 
      ? (attendance.filter(a => a.present).length / attendance.length) * 100 
      : 100;

    const averageGrade = grades.length > 0 
      ? grades.reduce((sum, g) => sum + (g.value / g.maxValue), 0) / grades.length * 100
      : 0;

    return {
      grades,
      attendance,
      annotations,
      attendanceRate,
      averageGrade
    };
  };

  const renderStudentCard = (student: any) => {
    const data = getStudentData(student.id);

    return (
      <Card key={student.id} className="mb-6">
        <CardHeader>
          <div className="flex items-center space-x-4">
            <div className="bg-primary rounded-full p-3">
              <User className="h-6 w-6 text-primary-foreground" />
            </div>
            <div>
              <CardTitle>{student.name}</CardTitle>
              <CardDescription>
                RUT: {student.rut} | Curso: {student.grade} {student.section}
              </CardDescription>
            </div>
          </div>
        </CardHeader>

        <CardContent>
          <Tabs defaultValue="overview" className="space-y-4">
            <TabsList className="grid w-full grid-cols-4">
              <TabsTrigger value="overview">Resumen</TabsTrigger>
              <TabsTrigger value="grades">Notas</TabsTrigger>
              <TabsTrigger value="attendance">Asistencia</TabsTrigger>
              <TabsTrigger value="annotations">Anotaciones</TabsTrigger>
            </TabsList>

            <TabsContent value="overview" className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Promedio General</CardTitle>
                    <TrendingUp className="h-4 w-4 text-muted-foreground" />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">
                      {data.averageGrade > 0 ? `${data.averageGrade.toFixed(1)}%` : 'Sin datos'}
                    </div>
                    <Progress value={data.averageGrade} className="mt-2" />
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Asistencia</CardTitle>
                    <Calendar className="h-4 w-4 text-muted-foreground" />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">{data.attendanceRate.toFixed(1)}%</div>
                    <Progress value={data.attendanceRate} className="mt-2" />
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                    <CardTitle className="text-sm font-medium">Evaluaciones</CardTitle>
                    <BookOpen className="h-4 w-4 text-muted-foreground" />
                  </CardHeader>
                  <CardContent>
                    <div className="text-2xl font-bold">{data.grades.length}</div>
                    <p className="text-xs text-muted-foreground">este período</p>
                  </CardContent>
                </Card>
              </div>

              <Card>
                <CardHeader>
                  <CardTitle className="text-lg">Estado Académico</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <span>Rendimiento Académico</span>
                      <Badge variant={data.averageGrade >= 70 ? "default" : "destructive"}>
                        {data.averageGrade >= 70 ? "Satisfactorio" : "Requiere Atención"}
                      </Badge>
                    </div>
                    <div className="flex items-center justify-between">
                      <span>Asistencia</span>
                      <Badge variant={data.attendanceRate >= 85 ? "default" : "destructive"}>
                        {data.attendanceRate >= 85 ? "Adecuada" : "Requiere Mejora"}
                      </Badge>
                    </div>
                    <div className="flex items-center justify-between">
                      <span>Conducta</span>
                      <Badge variant="default">Sin observaciones</Badge>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            <TabsContent value="grades" className="space-y-4">
              {data.grades.length === 0 ? (
                <Card>
                  <CardContent className="flex flex-col items-center justify-center py-8">
                    <BookOpen className="h-12 w-12 text-muted-foreground mb-4" />
                    <p className="text-muted-foreground">No hay calificaciones registradas</p>
                  </CardContent>
                </Card>
              ) : (
                <div className="space-y-3">
                  {data.grades
                    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
                    .map(grade => {
                      const percentage = (grade.value / grade.maxValue) * 100;
                      return (
                        <Card key={grade.id}>
                          <CardContent className="flex items-center justify-between p-4">
                            <div>
                              <p className="font-medium">{grade.subject}</p>
                              <p className="text-sm text-muted-foreground">
                                {grade.type} - {new Date(grade.date).toLocaleDateString('es-CL')}
                              </p>
                            </div>
                            <div className="text-right">
                              <p className="font-bold text-lg">{grade.value}</p>
                              <Badge variant={percentage >= 60 ? "default" : "destructive"}>
                                {percentage.toFixed(0)}%
                              </Badge>
                            </div>
                          </CardContent>
                        </Card>
                      );
                    })}
                </div>
              )}
            </TabsContent>

            <TabsContent value="attendance" className="space-y-4">
              {data.attendance.length === 0 ? (
                <Card>
                  <CardContent className="flex flex-col items-center justify-center py-8">
                    <Calendar className="h-12 w-12 text-muted-foreground mb-4" />
                    <p className="text-muted-foreground">No hay registros de asistencia</p>
                  </CardContent>
                </Card>
              ) : (
                <div className="space-y-3">
                  {data.attendance
                    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
                    .map(record => (
                      <Card key={record.id}>
                        <CardContent className="flex items-center justify-between p-4">
                          <div className="flex items-center space-x-3">
                            {record.present ? (
                              <CheckCircle className="h-5 w-5 text-green-500" />
                            ) : (
                              <XCircle className="h-5 w-5 text-red-500" />
                            )}
                            <div>
                              <p className="font-medium">
                                {new Date(record.date).toLocaleDateString('es-CL', {
                                  weekday: 'long',
                                  year: 'numeric',
                                  month: 'long',
                                  day: 'numeric'
                                })}
                              </p>
                              <p className="text-sm text-muted-foreground">
                                Clase ID: {record.classId}
                              </p>
                            </div>
                          </div>
                          <Badge variant={record.present ? "default" : "destructive"}>
                            {record.present ? "Presente" : "Ausente"}
                          </Badge>
                        </CardContent>
                      </Card>
                    ))}
                </div>
              )}
            </TabsContent>

            <TabsContent value="annotations" className="space-y-4">
              {data.annotations.length === 0 ? (
                <Card>
                  <CardContent className="flex flex-col items-center justify-center py-8">
                    <AlertTriangle className="h-12 w-12 text-muted-foreground mb-4" />
                    <p className="text-muted-foreground">No hay anotaciones registradas</p>
                  </CardContent>
                </Card>
              ) : (
                <div className="space-y-3">
                  {data.annotations
                    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
                    .map(annotation => (
                      <Card key={annotation.id} className={`border-l-4 ${
                        annotation.type === 'positiva' ? 'border-l-green-500' :
                        annotation.type === 'negativa' ? 'border-l-red-500' :
                        'border-l-yellow-500'
                      }`}>
                        <CardContent className="p-4">
                          <div className="flex items-center justify-between mb-2">
                            <Badge variant={
                              annotation.type === 'positiva' ? "default" :
                              annotation.type === 'negativa' ? "destructive" :
                              "secondary"
                            }>
                              {annotation.type === 'positiva' ? "Positiva" :
                               annotation.type === 'negativa' ? "Negativa" :
                               "Observación"}
                            </Badge>
                            <span className="text-sm text-muted-foreground">
                              {new Date(annotation.date).toLocaleDateString('es-CL')}
                            </span>
                          </div>
                          <p>{annotation.content}</p>
                        </CardContent>
                      </Card>
                    ))}
                </div>
              )}
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    );
  };

  return (
    <div className="p-4 md:p-6 space-y-6">
      <div>
        <h2 className="text-2xl font-semibold mb-2">Mis Hijos</h2>
        <p className="text-muted-foreground">
          Información académica detallada de tus estudiantes.
        </p>
      </div>

      {myStudents.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-8">
            <User className="h-12 w-12 text-muted-foreground mb-4" />
            <h3 className="text-lg font-semibold mb-2">No hay estudiantes registrados</h3>
            <p className="text-muted-foreground text-center">
              No se encontraron estudiantes asociados a tu cuenta de apoderado.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div>
          {myStudents.map(renderStudentCard)}
        </div>
      )}
    </div>
  );
};

// Fase 2/Evidencias Proyecto/Evidencias de sistema Aplicación/Plataforma de Gestión Escolar/src/components/StudentView.vue
<template>
  <div class="p-4 md:p-6">
    <div class="mb-6">
      <h1 class="text-2xl font-bold text-foreground">
        {{ getViewTitle() }}
      </h1>
      <p class="text-muted-foreground mt-1">
        {{ getViewDescription() }}
      </p>
    </div>

    <div v-if="isLoading" class="flex items-center justify-center py-8">
      <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
    </div>

    <div v-else-if="students.length === 0" class="text-center py-8">
      <div class="w-16 h-16 bg-muted rounded-full flex items-center justify-center mx-auto mb-4">
        <UsersIcon class="h-8 w-8 text-muted-foreground" />
      </div>
      <h3 class="text-lg font-medium text-foreground mb-2">No hay estudiantes</h3>
      <p class="text-muted-foreground">No se encontraron estudiantes para mostrar.</p>
    </div>

    <div v-else class="space-y-6">
      <!-- Students Grid -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div
          v-for="student in students"
          :key="student.id"
          class="bg-card border border-border rounded-lg p-6 hover:shadow-md transition-shadow cursor-pointer"
          @click="selectStudent(student)"
        >
          <div class="flex items-center space-x-4 mb-4">
            <div class="w-12 h-12 bg-primary rounded-full flex items-center justify-center">
              <span class="text-primary-foreground font-medium text-lg">
                {{ student.name.charAt(0) }}
              </span>
            </div>
            <div>
              <h3 class="font-semibold text-foreground">{{ student.name }}</h3>
              <p class="text-sm text-muted-foreground">{{ student.course }}</p>
            </div>
          </div>

          <div class="space-y-2">
            <!-- Latest grade -->
            <div v-if="student.grades && student.grades.length > 0" class="flex items-center justify-between">
              <span class="text-sm text-muted-foreground">Última calificación:</span>
              <span class="font-medium text-foreground">
                {{ student.grades[0].grade }} ({{ student.grades[0].subject }})
              </span>
            </div>

            <!-- Attendance status -->
            <div v-if="student.attendance && student.attendance.length > 0" class="flex items-center justify-between">
              <span class="text-sm text-muted-foreground">Última asistencia:</span>
              <span 
                class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium"
                :class="getAttendanceClasses(student.attendance[0].status)"
              >
                {{ getAttendanceLabel(student.attendance[0].status) }}
              </span>
            </div>

            <!-- Average grade -->
            <div v-if="student.grades && student.grades.length > 0" class="flex items-center justify-between">
              <span class="text-sm text-muted-foreground">Promedio:</span>
              <span class="font-medium text-foreground">
                {{ calculateAverage(student.grades) }}
              </span>
            </div>
          </div>
        </div>
      </div>

      <!-- Selected student details modal -->
      <div
        v-if="selectedStudent"
        class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-50"
        @click="closeStudentDetails"
      >
        <div
          class="bg-card rounded-lg border border-border p-6 max-w-2xl w-full max-h-[80vh] overflow-y-auto"
          @click.stop
        >
          <div class="flex items-center justify-between mb-6">
            <h2 class="text-xl font-bold text-foreground">{{ selectedStudent.name }}</h2>
            <button
              @click="closeStudentDetails"
              class="p-2 hover:bg-muted rounded-lg"
            >
              <CloseIcon class="h-5 w-5" />
            </button>
          </div>

          <div class="space-y-6">
            <!-- Student info -->
            <div class="bg-muted rounded-lg p-4">
              <h3 class="font-medium text-foreground mb-2">Información General</h3>
              <div class="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span class="text-muted-foreground">Curso:</span>
                  <span class="ml-2 text-foreground">{{ selectedStudent.course }}</span>
                </div>
                <div>
                  <span class="text-muted-foreground">ID:</span>
                  <span class="ml-2 text-foreground">{{ selectedStudent.id }}</span>
                </div>
              </div>
            </div>

            <!-- Grades -->
            <div v-if="selectedStudent.grades && selectedStudent.grades.length > 0">
              <h3 class="font-medium text-foreground mb-3">Calificaciones Recientes</h3>
              <div class="space-y-2">
                <div
                  v-for="grade in selectedStudent.grades"
                  :key="`${grade.subject}-${grade.date}`"
                  class="flex items-center justify-between p-3 bg-muted rounded-lg"
                >
                  <div>
                    <span class="font-medium text-foreground">{{ grade.subject }}</span>
                    <span class="text-sm text-muted-foreground ml-2">{{ formatDate(grade.date) }}</span>
                  </div>
                  <span class="text-lg font-bold text-foreground">{{ grade.grade }}</span>
                </div>
              </div>
            </div>

            <!-- Attendance -->
            <div v-if="selectedStudent.attendance && selectedStudent.attendance.length > 0">
              <h3 class="font-medium text-foreground mb-3">Asistencia Reciente</h3>
              <div class="space-y-2">
                <div
                  v-for="attendance in selectedStudent.attendance"
                  :key="attendance.date"
                  class="flex items-center justify-between p-3 bg-muted rounded-lg"
                >
                  <span class="text-foreground">{{ formatDate(attendance.date) }}</span>
                  <span 
                    class="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium"
                    :class="getAttendanceClasses(attendance.status)"
                  >
                    {{ getAttendanceLabel(attendance.status) }}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useAuthStore } from '../stores/authStore'
import { mockStudents } from '../data/mockData'

const authStore = useAuthStore()

// State
const isLoading = ref(false)
const selectedStudent = ref(null)

// Icons
const UsersIcon = {
  template: `<svg class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197m-3 5.197H7v-1a6 6 0 0112 0v1z" />
  </svg>`
}

const CloseIcon = {
  template: `<svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
  </svg>`
}

// Computed properties
const students = computed(() => {
  const role = authStore.user?.role
  
  if (role === 'apoderado') {
    // Show only children of this parent
    return mockStudents.filter(student => student.parentId === authStore.user.id)
  } else if (role === 'docente') {
    // Show students from teacher's courses (simplified)
    return mockStudents
  } else if (role === 'coordinador') {
    // Show all students
    return mockStudents
  }
  
  return []
})

// Methods
const getViewTitle = () => {
  const role = authStore.user?.role
  const titles = {
    coordinador: 'Gestión de Estudiantes',
    docente: 'Mis Estudiantes',
    apoderado: 'Mis Hijos'
  }
  return titles[role] || 'Estudiantes'
}

const getViewDescription = () => {
  const role = authStore.user?.role
  const descriptions = {
    coordinador: 'Administra y supervisa a todos los estudiantes del colegio',
    docente: 'Gestiona y hace seguimiento a tus estudiantes',
    apoderado: 'Consulta el progreso académico y asistencia de tus hijos'
  }
  return descriptions[role] || ''
}

const selectStudent = (student) => {
  selectedStudent.value = student
}

const closeStudentDetails = () => {
  selectedStudent.value = null
}

const getAttendanceClasses = (status) => {
  const classes = {
    presente: 'bg-green-100 text-green-800',
    ausente: 'bg-red-100 text-red-800',
    tarde: 'bg-yellow-100 text-yellow-800'
  }
  return classes[status] || 'bg-gray-100 text-gray-800'
}

const getAttendanceLabel = (status) => {
  const labels = {
    presente: 'Presente',
    ausente: 'Ausente',
    tarde: 'Tarde'
  }
  return labels[status] || status
}

const calculateAverage = (grades) => {
  if (!grades || grades.length === 0) return 'N/A'
  const sum = grades.reduce((acc, grade) => acc + grade.grade, 0)
  return (sum / grades.length).toFixed(1)
}

const formatDate = (dateString) => {
  const date = new Date(dateString)
  return date.toLocaleDateString('es-CL', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  })
}

// Lifecycle
onMounted(() => {
  // Simulate loading
  isLoading.value = true
  setTimeout(() => {
    isLoading.value = false
  }, 500)
})
</script>
